package ManagementPackage;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author V.T
 */
public class adminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form adminHomePage
     */
    public adminHomePage() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        newStudentBtn = new javax.swing.JButton();
        newResultBtn = new javax.swing.JButton();
        studentListBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        resultsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 590));
        setMinimumSize(new java.awt.Dimension(700, 590));
        setPreferredSize(new java.awt.Dimension(700, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setBackground(new java.awt.Color(204, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-logout-30.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 220, 40));

        newStudentBtn.setBackground(new java.awt.Color(204, 255, 255));
        newStudentBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        newStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-resume-30.png"))); // NOI18N
        newStudentBtn.setText("Add New Student");
        newStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 40));

        newResultBtn.setBackground(new java.awt.Color(204, 255, 255));
        newResultBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        newResultBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-add-properies-30.png"))); // NOI18N
        newResultBtn.setText("Add New Result");
        newResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResultBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newResultBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 40));

        studentListBtn.setBackground(new java.awt.Color(204, 255, 255));
        studentListBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        studentListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-list-30.png"))); // NOI18N
        studentListBtn.setText("Students List");
        studentListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentListBtnActionPerformed(evt);
            }
        });
        getContentPane().add(studentListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, 40));

        updateStudentBtn.setBackground(new java.awt.Color(204, 255, 255));
        updateStudentBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        updateStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-writer-female-30.png"))); // NOI18N
        updateStudentBtn.setText("Update Student");
        updateStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 220, 40));

        resultsBtn.setBackground(new java.awt.Color(204, 255, 255));
        resultsBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        resultsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/icons8-report-card-30.png"))); // NOI18N
        resultsBtn.setText("Student Results");
        resultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagementPackage/Screenshot 2022-10-25 at 2.52.05 PM.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResultBtnActionPerformed
        addResult frame = new addResult();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_newResultBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int flag = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Submit", JOptionPane.YES_NO_OPTION);
        if(flag==0){
            setVisible(false);
            HomePage frame = new HomePage();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void resultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBtnActionPerformed
          listStudentResult frame = new listStudentResult();
          frame.setVisible(true);
          frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_resultsBtnActionPerformed

    private void newStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentBtnActionPerformed
        addStudent frame = new addStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_newStudentBtnActionPerformed

    private void studentListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentListBtnActionPerformed
        studentsList frame = new studentsList();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_studentListBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed
        updateStudent frame = new updateStudent();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton newResultBtn;
    private javax.swing.JButton newStudentBtn;
    private javax.swing.JButton resultsBtn;
    private javax.swing.JButton studentListBtn;
    private javax.swing.JButton updateStudentBtn;
    // End of variables declaration//GEN-END:variables
}
